name: service-ci

# Controls when the workflow will run
on: [pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  proto_checks:
    name: proto lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: '0.36.0'
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      
      - name: Fetching base branch
        run: |
                git fetch -u origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Running linter
        run: |
                buf lint
