name: service-ci

# Controls when the workflow will run
on: [pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-service:
    env: 
      BUILD_CONFIG: "Release"
      BUILD_DESTINATION: "build"
    name: Build service
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Restore nuget packages
        run: dotnet restore
        
      - name: Build solution
        run: dotnet build -c $BUILD_CONFIG --no-restore -o $BUILD_DESTINATION
      
      - name: Uplaod artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: $BUILD_DESTINATION
        
