name: Nuget-CI

on: [workflow_dispatch]

jobs:
  build-nuget:
    env: 
      BUILD_CONFIG: "Release"
      BUILD_DESTINATION: "package"
    name: Build Nuget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore
        run: dotnet restore
      - name: Build Solution
        run: dotnet build -c $BUILD_CONFIG --no-restore -o $BUILD_DESTINATION
      - name: Tests
        run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
      - name: Publish Github
        run: dotnet nuget push "$BUILD_DESTINATION\**\*.nupkg"  --api-key $NUGET_TOKEN --source "github"
